### ISSUE TITLE
Is it possible to predict hand pose with the pretrained model ?

### ISSUE THREAD

**Issue by PascalYIN** [xkunwu/depth-hand#8]
Hello @xkunwu,

Thanks for your great job! 

You precised the command line of basic usage of the pretrained model, however to realise the evaluation your code always tries to find the hands2017's annotation text file.  As I am currently not capable of  getting the raw data, I would like to know if there is a way to use the pretrained model for prediction without ground truth files.  

Thanks!

**Comment by xkunwu** [comment]
Short answer is yes: of course you should be able to reproduce the same result as the demo capture sequence, or produce detection results on your own depth camera. When I last tested the code for writing the "quick start" section, I do not even have the data on my laptop as you did.

"evaluation" serves research purpose and should be invoked to reproduce the results in my ECCV'18 paper. This function do require the raw data since it meant for evaluation as the name suggested, but I cannot redistribute it.

I guess you would like to use the pre-trained model to work on real depth streams, then follow the instructions of tracking part of the code and you'll rock :)

**Comment by PascalYIN** [comment]
Thanks for your response, I will try that :)
